### ISSUE TITLE
Kafka Kraft no longer works on ubuntu-latest

### ISSUE THREAD

**Issue by dixonmyles** [spicyparrot/kafka-kraft-action#15]
**Describe the bug**
Kafka Kraft action fails on ubuntu-latest due to deprecation of docker compose v1.

**To Reproduce**
1. Run any job using Kafka Kraft v1.1.1
2. Observe error in `./scripts/start.sh` - `docker-compose: command not found`
3. Job fails.

**Expected behavior**
Job should succeed

**Screenshots**
![image](https://github.com/user-attachments/assets/54e998f4-98a7-47df-8e24-71f12d51df6f)
(removed topic names)

**Additional context**
The team maintaining the `actions/runner-images` repository pushed the following pull request on July 30th:
- https://github.com/actions/runner-images/pull/10368

This PR removed support for Docker Compose v1.

The suggested fix would be to migrate the `docker-compose up -d` command in `scripts/start.sh` to use v2 as laid out [here](https://docs.docker.com/compose/migrate/)

**Comment by jdickson1992** [comment]
Really sorry about the delay - I've been travelling!

Thanks for digging into this and providing a resolution - love the write up.

@asheswook and @benjylxwang kindly raised PRs that have been now been merged 👏

This should now be resolved in `spicyparrot/kafka-kraft-action@v1.1.3` (_latest version_).
